name: exchangeview
description: A simple CLI tool to help with currency conversion and other calculations related to invoicing.
version: 1.0.0
homepage: https://github.com/jeroen-meijer/exchangeview

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  args: ^1.6.0
  cli_util: ^0.2.0
  http: ^0.12.1
  intl: ^0.16.1
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.9.0
